---
# tasks file for jenkins

- name: install java
  apt:
    name: openjdk-8-jdk
    state: present

- name: Add Jenkins apt installation.
  get_url:
    url: "{{ jenkins_url }}"
    dest: /etc/apt/trusted.gpg.d/jenkins.asc
    mode: '0644'
    force: true
      
- name: Add Jenkins 
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: true
    when: jenkins_repo_url | default(false)
  
- name: install jenkins
  apt:
    name: install jenkins 
    state: present

- name: Ensure Jenkins is started and runs on startup.
  service: name=jenkins state=started enabled=yes
  notify:
     - start jenkins

- name: configure default users
  template:
    src: basic-security.groovy.j2
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  notify:
    - Restart jenkins





